#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--pagesize", default=4096, type=int)
args = parser.parse_args()
page_size = args.pagesize

size_classes = [
    16, 32, 48, 64, 80, 96, 112, 128,
    160, 192, 224, 256,
    320, 384, 448, 512,
    640, 768, 896, 1024,
    1280, 1536, 1792, 2048,
    2560, 3072, 3584, 4096,
    5120, 6144, 7168, 8192,
    10240, 12288, 14336, 16384,
    20480, 24576, 28672, 32768,
    40960, 49152, 57344, 65536,
    81920, 98304, 114688, 131072,
]

size_class_slots_4k = [
    256, 128, 85, 64, 51, 42, 36, 64,
    51, 64, 54, 64,
    64, 64, 64, 64,
    64, 64, 64, 64,
    16, 16, 16, 16,
    8, 8, 8, 8,
    8, 8, 8, 8,
    6, 5, 4, 4,
    2, 2, 2, 2,
    1, 1, 1, 1,
    1, 1, 1, 1,
]

size_class_slots_16k = [
    256, 256, 256, 256,
    204, 170, 146, 256,
    204, 256, 219, 256,
    256, 256, 256, 256,
    256, 256, 256, 256,
    192, 160, 128, 128,
    96, 80, 64, 64,
    48, 40, 32, 32,
    24, 20, 16, 16,
    12, 10, 8, 8,
    6, 5, 4, 4,
    3, 2, 2, 2,
]

if page_size == 16384:
    size_class_slots = size_class_slots_16k
else:
    size_class_slots = size_class_slots_4k

fragmentation = [100 - 1 / 16 * 100]

for i in range(len(size_classes) - 1):
    size_class = size_classes[i + 1]
    worst_case = size_classes[i] + 1
    used = worst_case / size_class
    fragmentation.append(100 - used * 100)


def page_align(size):
    mask = page_size - 1
    return (size + mask) & ~mask


print(f"Page size: {page_size}")
print()
print("| ", end="")
print(
    "size class",
    "worst case internal fragmentation",
    "slab slots",
    "slab size",
    "internal fragmentation for slabs",
    sep=" | ",
    end=" |\n",
)
print("| ", end="")
print("-", "-", "-", "-", "-", sep=" | ", end=" |\n")
for size, slots, fragmentation in zip(size_classes, size_class_slots, fragmentation):
    used = size * slots
    real = page_align(used)
    print("| ", end="")
    print(
        size,
        f"{fragmentation:.4}%",
        slots,
        real,
        str(100 - used / real * 100) + "%",
        sep=" | ",
        end=" |\n",
    )

max_bits = 256
max_page_span = 16

print()

print("maximum bitmap size is {}-bit".format(max_bits))
print( "maximum page span size is {} ({})".format(max_page_span, max_page_span * page_size))

for size_class in size_classes:
    choices = []
    for bits in range(1, max_bits + 1):
        used = size_class * bits
        real = page_align(used)
        if real > max_page_span * page_size:
            continue
        pages = real / page_size
        efficiency = used / real * 100
        choices.append((bits, used, real, pages, efficiency))

    choices.sort(key=lambda x: x[4], reverse=True)

    print()
    print("size_class:", size_class)
    for choice in choices[:10]:
        print(choice)
