name: Build and run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-ubuntu-gcc:
    runs-on: ubuntu-latest
    container:
      image: debian:testing-slim
    strategy:
      matrix:
        version: [14, 15, 16]
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends ca-certificates git make python3 gcc-${{ matrix.version }} g++-${{ matrix.version }}
      - uses: actions/checkout@v6
      - name: Build
        run: CC=gcc-${{ matrix.version }} CXX=g++-${{ matrix.version }} make test
      - name: Build with MADV_GUARD_INSTALL guard pages
        run: make clean && CC=gcc-${{ matrix.version }} CXX=g++-${{ matrix.version }} make test CONFIG_GUARD_PAGES_USE_MADVISE=true
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [19, 20]
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends clang-19 clang-20
      - name: Setting up clang version
        run: |
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ matrix.version }} 100
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ matrix.version }} 100
      - name: Build
        run: CC=clang CXX=clang++ make test
      - name: Build with MADV_GUARD_INSTALL guard pages
        run: make clean && CC=clang CXX=clang++ make test CONFIG_GUARD_PAGES_USE_MADVISE=true
  build-musl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: apk update && apk add build-base python3
      - name: Build
        run: make test
      - name: Build with MADV_GUARD_INSTALL guard pages
        run: make clean && make test CONFIG_GUARD_PAGES_USE_MADVISE=true
  build-ubuntu-gcc-aarch64:
    runs-on: ubuntu-latest
    container:
      image: debian:testing-slim
    strategy:
      matrix:
        version: [14, 15, 16]
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends ca-certificates git make gcc-${{ matrix.version }}-aarch64-linux-gnu g++-${{ matrix.version }}-aarch64-linux-gnu cpp-${{ matrix.version }}-aarch64-linux-gnu
      - uses: actions/checkout@v6
      - name: Build
        run: CC=aarch64-linux-gnu-gcc-${{ matrix.version }} CXX=aarch64-linux-gnu-g++-${{ matrix.version }} make CONFIG_NATIVE=false
